"""Add tag field to Offer table

Revision ID: e69922ac488e
Revises: 202c122d443e
Create Date: 2024-04-24 22:21:42.561608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69922ac488e'
down_revision: Union[str, None] = '202c122d443e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'tag')
    # ### end Alembic commands ###
